services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - flask_network

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
